const DOC_PATH = '/doc';

const CONTENT_PATH = '/content';

// component names
const DRAWER_NAME = '/drawer';
const SWITCH_NAME = '/switch';
const BUTTON_NAME = '/button';
const OVERLAY_NAME = '/overlay';
const ICON_NAME = '/icon';
const NUMBER_INPUT_NAME = '/number-input';
const NAVBAR_NAME = '/navbar';

const DocUrls = {
	DOC_PATH,
	CONTENT_PATH,
	Content: {
		DRAWER_CONTENT_PATH: `${DOC_PATH}${CONTENT_PATH}${DRAWER_NAME}`,
		SWITCH_CONTENT_PATH: `${DOC_PATH}${CONTENT_PATH}${SWITCH_NAME}`,
		BUTTON_CONTENT_PATH: `${DOC_PATH}${CONTENT_PATH}${BUTTON_NAME}`,
		OVERLAY_CONTENT_PATH: `${DOC_PATH}${CONTENT_PATH}${OVERLAY_NAME}`,
		ICON_CONTENT_PATH: `${DOC_PATH}${CONTENT_PATH}${ICON_NAME}`,
		NUMBER_INPUT_CONTENT_PATH: `${DOC_PATH}${CONTENT_PATH}${NUMBER_INPUT_NAME}`,
		NAVBAR_CONTENT_PATH: `${DOC_PATH}${CONTENT_PATH}${NAVBAR_NAME}`,
	},
	Main: {
		DRAWER_PATH: `${DOC_PATH}${DRAWER_NAME}`,
		SWITCH_PATH: `${DOC_PATH}${SWITCH_NAME}`,
		BUTTON_PATH: `${DOC_PATH}${BUTTON_NAME}`,
		OVERLAY_PATH: `${DOC_PATH}${OVERLAY_NAME}`,
		ICON_PATH: `${DOC_PATH}${ICON_NAME}`,
		NUMBER_INPUT_PATH: `${DOC_PATH}${NUMBER_INPUT_NAME}`,
		NAVBAR_PATH: `${DOC_PATH}${NAVBAR_NAME}`,
	},
};

export default DocUrls;
